title: 'Apanage CBD, boutique en ligne, garantie qualité'
email: contact@apanagecbd.com
description: >-
  Le meilleur du CBD garanti zéro THC. Tous nos produits sont de qualité
  ultra-premium; ils sont fabriqués par des producteurs haut de gamme, selon des
  process à la pointe de l’industrie du CBD.
baseurl: /
url: 'https://apanagecbd.com'
twitter_username: ''
github_username: ''
plugins:
  - jekyll-feed
collections:
  products:
    output: true
  customers: null
snipcartApiKey: YzUzYjE0NGItOTE1Zi00M2RhLTgyYTMtYzQyNjMzMGQwYjJlNjM3MDQ0MTcyOTI4Nzc5NzI5
currency: €
defaults:
  - scope:
      path: ''
      type: products
    values:
      layout: product-page
