title: 'Feel good, CBD boutique en ligne, garantie qualité'
email: contact@weedy.com
description: >-
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: /
url: 'https://apanagecbd.com'
twitter_username: ''
github_username: ''
plugins:
  - jekyll-feed
collections:
  - products
  - customers

snipcartApiKey: 'YzUzYjE0NGItOTE1Zi00M2RhLTgyYTMtYzQyNjMzMGQwYjJlNjM3MDQ0MTcyOTI4Nzc5NzI5'
currency: '€'
