title: 'Apanage CBD Shop, boutique en ligne'
email: contact@apanagecbd.com
description: >-
CBD de qualité ULTRA-PREMIUM, garanti ZÉRO THC détectable en cas de test de dépistage.
baseurl: '/'
url: 'https://apanagecbd.com'
twitter_username: ''
github_username: ''
plugins:
  - jekyll-feed
collections:
  products:
    output: true
  customers: null
snipcartApiKey: YzUzYjE0NGItOTE1Zi00M2RhLTgyYTMtYzQyNjMzMGQwYjJlNjM3MDQ0MTcyOTI4Nzc5NzI5
currency: €
defaults:
  - scope:
      path: ''
      type: products
    values:
      layout: product-page
